#!/bin/bash
function gen_conf(){
echo "ota_url=https://raw.githubusercontent.com/Cosmic-OS/ota/master/$TARGET_DEVICE.xml"
echo "release_type=Stable"
echo "device_name=ro.product.device"
echo "version_source=ro.mod.version"
echo "version_delimiter=_"
echo "version_position=3"
echo "version_format=yyyyMMdd"
}

gen_conf > $LOCAL_PATH/app/src/main/assets/ota_conf
